rainforest/config/routes.rb
Rainforest::Application.routes.draw do
  get "reviews/show"
  get "reviews/new"
  get "reviews/edit"
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "users/new"
  get "users/create"
  resources :products
  resources :users, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :products do 
    resources :reviews, :except => [:index]
    end

end

rainforest/app/models/product.rb
class Product < ActiveRecord::Base
	has_many :reviews
	has_many :users, :through => :reviews

	validates :description, :name, :presence => true
	validates :price_in_cents, :numericality => {:only_integer => true}

  	def formatted_price
    	price_in_dollars = price_in_cents.to_f / 100
    	sprintf("%.2f", price_in_dollars)
	end
end

rainforest/app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :product
	belongs_to :user

	validates :comment, :presence => true
end

rainforest/app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :reviews
	has_many :products, :through => :reviews

	validates_presence_of :name
end

rainforest/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def ensure_logged_in
  	unless current_user
  		flash[:alert] = "Please log in"
  		redirect_to new_session_path
  	end
  end

  private

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

rainforest/app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
  	  @products = Product.order('products.created_at DESC').page(params[:page])
      
      respond_to do |format|
        format.js
        format.html
      end
    end

    def show
  	  @product = Product.find(params[:id])

      if current_user
        @review = @product.reviews.build
      end
    end

    def new
  	  @product = Product.new
    end

    def edit
    	@product = Product.find(params[:id])
    end

  	def create
  		@product = Product.new(product_params)

  		if @product.save
  			redirect_to products_url
  		else
  			render :new
  		end
   	end

   	def update
   		@product = Product.find(params[:id])

   		if @product.update_attributes(product_params)
   			redirect_to product_path(@product)
   		else
   			render :edit
   		end
   	end

   	def destroy
   		@product = Product.find(params[:id])
   		@product.destroy
   		redirect_to products_path
   	end

   	private
   	def product_params
   		params.require(:product).permit(:name, :description, :price_in_cents)
   	end
end

rainforest/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_filter :ensure_logged_in, :only => [:show]
	before_filter :load_product

  def show
  	@review = Review.find(params[:id])
  end

  def create
  	@review = @product.reviews.build(review_params)
  	@review.user_id = current_user.id

    respond_to do |format|  
    	if @review.save
    		format.html { redirect_to products_path(@product.id), notice: 'Review added.' }
        format.js {} 
    	else
        format.html { render 'products/show', alert: 'There was an error.' }
        format.js {}
    	end
    end
  end

  def destroy
  	@review = Review.find(params[:id])
  	@review.destroy
  end

  private
  def review_params
  	params.require(:review).permit(:comment, :product_id)
  end

  def load_product
  	@product = Product.find(params[:product_id])
  end
end

rainforest/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to products_url, :notice => "Logged in!"
  	else
  		flash.now[:alert] = "Invalid email or password"
  		render 'new'
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to products_url, :notice => "Logged out!"
  end
end

rainforest/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to products_url, :notice => "Account Created!"
  	else
  		render 'new'
  	end
  end

  private 
  def user_params
  	params.require(:user).permit(:name, :email, :password, :password_confirmation, :name)
  end
end

rainforest/app/helpers/application_helper.rb
module ApplicationHelper
end

rainforest/app/helpers/products_helper.rb
module ProductsHelper
end

rainforest/app/helpers/reviews_helper.rb
module ReviewsHelper
end

rainforest/app/helpers/sessions_helper.rb
module SessionsHelper
end

rainforest/app/helpers/users_helper.rb
module UsersHelper
end

rainforest/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rainforest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash[:notice] %>
	<p id="notice"><%= flash[:notice] %></p>
<% end %>
<% if flash[:alert] %>
	<p id="alert"><%= flash[:alert] %></p>
<% end %>

<%= yield %>

	<p class="userinfo">
		<% if current_user %>
			Signed in as <%= current_user.name %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
		<% else %>
			<%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
		<% end %>
	</p>
</body>
</html>

rainforest/app/views/products/_form.html.erb
<%= form_for (@product) do |f| %>
	
	<% if @product.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@product.errors.count, "error") %>
				prohibited this product from being saved:</h2>
			<ul>
			<% @product.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>
	
	<div class="field">
		<%= f.label "name" %>
		<br>
		<%= f.text_field "name" %>
	</div>
	<div class="field">
		<%= f.label "description" %>
		<br>
		<%= f.text_field "description" %>
	</div>
	<div class="field">
		<%= f.label "price_in_cents" %>
		<br>
		<%= f.number_field "price_in_cents" %>
	</div>
	<div>
		<%= f.submit "Save" %>
	</div>
<% end %>

rainforest/app/views/products/_product.html.erb
	<p>	<%= link_to product.name, product %>
		<br>
		<br>
		<%= product.description %>
		<%= number_to_currency(product.formatted_price) %>
	</p>
	

	<p><%= truncate(product.description, length: 100) %></p>

rainforest/app/views/products/_review_form_errors.html.erb
<% if @review.errors.present? %>
	<% @review.errors.full_messages.each do |error| %>
		<div class="alert">
			<%= error %>
		</div>
	<% end %>
<% end %>

rainforest/app/views/products/_reviews.html.erb
<div id="review-list">
	<% @product.reviews.each do |review| %>
		<div class="comment">
			<%= review.comment %>
		</div>
			<br>
		<div class="poster">
			<% if review.user != nil %>
				<em> by <%= review.user.name %></em>
				Added on: <%= review.created_at %>
			<% end %>
		</div>
	<% end %>
</div>

rainforest/app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= link_to 'Back', products_path %>

<%= render 'form' %>

rainforest/app/views/products/index.html.erb
<h1>Products</h1>
<h2><%= page_entries_info @products %></h2>

<hr/>

<div id="products">
	<%= render @products %>
</div>

<hr/>

<%= paginate @products %>

<hr/>

<%= link_to 'Add a Product', 'products/new' %> 
<br>
<br>
<%= link_to 'Create an Account', 'users/new' %>

rainforest/app/views/products/index.js.erb
$('#products').append('<%= j render(@products) %>');
$('.pagination').replaceWith('<%= j paginate(@products) %>');

rainforest/app/views/products/new.html.erb
<h1>Add a New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

rainforest/app/views/products/show.html.erb
<h1>
	<%= @product.name %>
</h1>

<p>
	<%= @product.description %>
	<%= number_to_currency(@product.formatted_price) %>
</p>

<% if current_user %>

	<h2>Reviews</h2>

	<p>Reviews for <%= @product.name %></p>

<div id="review-list">
	<%= render :partial => "reviews" %>
</div>
	
<h4>New Review</h4>

<%= form_for [@product, @review], :remote => true do |f| %>
		
	<div id="review-form-errors">
		<%= render :partial => "/products/review_form_errors" %>
	</div>

	<div class="field">
		<%= f.label :comment %><br />
		<%= f.text_area :comment %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>
	<% end %>

	<% else %>
	<p>Please <%= link_to "log in", new_session_path %> to add a review.</p> 
	<% end %>

<br>
<br>

<%= link_to 'Back', products_path %>

<br>
<br>

<%= link_to 'Edit Product', edit_product_path %>

<br>
<br>

<%= link_to 'Delete Product', @product, :confirm => "Delete this Product?", :method => :delete %>

<script type="text/javascript">
	$(function(){
		$("#new_review")
		.on('ajax:BeforeSend', function(){
			$("input[type='submit']")
				.val('Saving...')
				.attr('disabled', 'disabled');
		});
		.on('ajax:complete', function(){
			$("input[type='submit']")
				.val('Create Review')
				.removeAttr('disabled');
		});
	});
</script>

rainforest/app/views/reviews/create.js.erb
<% if @review.errors.present? %>
	$("#review-form-errors").html("<%= escape_javascript(render(:partial => '/products/review-form-errors')) %>");
<% else %>
	$('#review-form-errors').html("");
	$('#review-list').html("<%= escape_javascript(render(:partial => 'products/reviews')) %>");
	$('#new_review')[0].reset();
<% end %>

rainforest/app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

rainforest/app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

rainforest/app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

rainforest/app/views/users/new.html.erb
<h1>Create an Account</h1>

<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div class="error_messages">
			<h2>Form is invalid</h2>
			<ul>
				<% for message in @user.errors.full_messages %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
<div class="field">
	<%= f.label :name%><br>
	<%= f.text_field :name %>
</div>
<div class="field">
	<%= f.label :email %><br>
	<%= f.text_field :email %>
</div>
<div class="field">
	<%= f.label :password %><br>
	<%= f.password_field :password %><br>
</div>
<div class="field">
	<%= f.label :password_confirmation %><br>
	<%= f.password_field :password_confirmation %>
</div>
<div class="actions"><%= f.submit %></div>
<% end %>